import os
from dotenv import load_dotenv

load_dotenv()

DISCORD_SNEAKER_WEBHOOK = os.getenv("DISCORD_SNEAKER_WEBHOOK")
DISCORD_KONG_WEBHOOK = os.getenv("DISCORD_KONG_WEBHOOK")
DISCORD_ROOKIE_WEBHOOK = os.getenv("DISCORD_ROOKIE_WEBHOOK")

TWEEPY_API_KEY = os.getenv("TWEEPY_API_KEY")
TWEEPY_API_SECRET = os.getenv("TWEEPY_API_SECRET")
TWEEPY_ACCESS_TOKEN = os.getenv("TWEEPY_ACCESS_TOKEN")
TWEEPY_ACCESS_TOKEN_SECRET = os.getenv("TWEEPY_ACCESS_TOKEN_SECRET")

OPENSEA_API_KEY = os.getenv("OPENSEA_API_KEY")

SLEEP_TIME = 60  # in seconds
ONE_HOUR_IN_SECONDS = 60 * SLEEP_TIME
OPENSEA_EVENTS_URL = "https://api.opensea.io/api/v2/events/collection/"

KONG_CONTRACT_ADDRESS = "0xef0182dc0574cd5874494a120750fd222fdb909a"
SNEAKER_CONTRACT_ADDRESS = "0x60E4d786628Fea6478F785A6d7e704777c86a7c6"
ROOKIE_CONTRACT_ADDRESS = "0x63f421b24cea6765b326753f6d4e558c21ea8f76"

KONG_ASSET_OPENSEA_URL = f"https://opensea.io/assets/{KONG_CONTRACT_ADDRESS}/"
SNEAKER_ASSET_OPENSEA_URL = f"https://opensea.io/assets/{SNEAKER_CONTRACT_ADDRESS}/"
ROOKIE_ASSET_OPENSEA_URL = f"https://opensea.io/assets/{ROOKIE_CONTRACT_ADDRESS}/"

HEADERS = {
    "X-API-KEY": OPENSEA_API_KEY,
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)"
    + " AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36",
}
